name: Shared-StaleBranch (deprecated)

on:
    workflow_call:
        inputs:
            PayloadJson:
                required: true
                type: string
            RepoBranchSkipList:
                required: true
                type: string
            ReportOnly:
                required: true
                type: boolean
        secrets:
            AccessToken:
                required: true

jobs:
    noop:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow is no longer in use. It has been moved to MicrosoftDocs/tcp-workflows."
