name: Shared-ExtractPayload (deprecated)

on:
    workflow_call:
        inputs:
            WorkflowId:
                required: true
                type: string
            OrgRepo:
                required: true
                type: string
        secrets:
            AccessToken:
                required: true
        outputs:
            WorkflowPayload:
                value: ${{ jobs.noop.outputs.JobPayload }}

jobs:
    noop:
        runs-on: ubuntu-latest
        outputs:
            JobPayload: '{}'
        steps:
            - run: echo "This workflow is no longer in use. It has been moved to MicrosoftDocs/tcp-workflows."
