name: Shared-Stale (deprecated)

on:
  workflow_call:
    inputs:
      RunDebug:
        type: boolean
        required: true
      RepoVisibility:
        type: string
        required: true
    secrets:
      AccessToken:
        required: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is no longer in use. It has been moved to MicrosoftDocs/tcp-workflows."
