name: Shared-GuidCheck (deprecated)

on:
  workflow_call:
    secrets:
      AccessToken:
        required: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is no longer in use. It has been moved to MicrosoftDocs/tcp-workflows."
